version: "3.3"

services:
    app:
        image: ghcr.io/developments-world/k1132-002:build
        environment:
            HOSTNAME: "{{.Node.Hostname}}-{{.Task.Slot}}"
            APP_ENV: 'production'
            APP_DEBUG: 'false'
            APP_KEY: ''
            APP_THEME: 'pterodactyl'
            APP_TIMEZONE: 'Europe/Berlin'
            APP_CLEAR_TASKLOG: '720'
            APP_DELETE_MINUTES: '10'
            APP_ENVIRONMENT_ONLY: 'false'
            LOG_CHANNEL: 'daily'
            APP_LOCALE: 'en'
            DB_HOST: ''
            DB_PORT: '3306'
            DB_DATABASE: 'panel'
            DB_USERNAME: 'pterodactyl'
            DB_PASSWORD: ''
            HASHIDS_SALT: ''
            HASHIDS_LENGTH: ''
            MAIL_DRIVER: 'array'
            MAIL_HOST: 'X.com'
            MAIL_PORT: '587'
            MAIL_USERNAME: 'X@X.com'
            MAIL_PASSWORD: ''
            MAIL_ENCRYPTION: 'tls'
            MAIL_FROM: 'X@X.com'
            QUEUE_HIGH: 'high'
            QUEUE_STANDARD: 'standard'
            QUEUE_LOW: 'low'
            APP_SERVICE_AUTHOR: 'X@X.com'
            APP_URL: ''
            CACHE_DRIVER: 'redis'
            SESSION_DRIVER: 'database'
            QUEUE_CONNECTION: 'database'
            SESSION_SECURE_COOKIE: 'true'
            REDIS_HOST: 'localhost'
            REDIS_PASSWORD: 'null'
            REDIS_PORT: '6379'
            MAIL_FROM_NAME: 'X'
            APP_API_CLIENT_RATELIMIT: '10000'
            APP_API_APPLICATION_RATELIMIT: '10000'
        ports:
            - target: 80
              published: 80
        deploy:
            placement:
                constraints:
                    - node.role == worker
            mode: replicated
            replicas: 3
            update_config:
                failure_action: rollback
                parallelism: 2
                delay: 15s
            restart_policy:
                condition: on-failure
